# Generated by Django 5.0.3 on 2024-03-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketTools", "0002_alter_resultgeo_unnamed_0"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultgeo",
            name="area",
        ),
        migrations.AlterField(
            model_name="resultgeo",
            name="unnamed_0",
            field=models.IntegerField(),
        ),
    ]
