# Generated by Django 5.0.3 on 2024-03-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketTools", "0007_delete_existinstalledgeo"),
    ]

    operations = [
        migrations.CreateModel(
            name="existInstalledGEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unnamed_0", models.IntegerField(blank=True, null=True)),
                ("installation_year", models.IntegerField()),
                ("address", models.CharField(max_length=255)),
                ("charging_station_name", models.CharField(max_length=255)),
                ("facility_category_large", models.CharField(max_length=255)),
                ("facility_category_small", models.CharField(max_length=255)),
                ("model_type_large", models.CharField(max_length=255)),
                ("model_type_small", models.CharField(max_length=255)),
                ("operating_organization_large", models.CharField(max_length=255)),
                ("operating_organization_small", models.CharField(max_length=255)),
                ("charger_type", models.CharField(max_length=255)),
                ("user_restriction", models.CharField(max_length=255)),
                ("charger_id", models.IntegerField()),
                ("charging_station_id", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
