# Generated by Django 5.0.3 on 2024-03-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketTools", "0008_existinstalledgeo"),
    ]

    operations = [
        migrations.CreateModel(
            name="existInstalledGridGEO",
            fields=[
                ("unnamed_0", models.IntegerField(blank=True, null=True)),
                ("fid", models.IntegerField()),
                (
                    "gid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("emd_cd", models.IntegerField()),
                ("emd_nm_k", models.CharField(max_length=255)),
                ("charging_station_accessibility", models.FloatField()),
                ("gas_station_count", models.IntegerField()),
                ("charging_station_count", models.IntegerField()),
                ("performance_facility_accessibility", models.FloatField()),
                ("public_price", models.FloatField()),
                ("library_accessibility", models.FloatField()),
                ("hospital_accessibility", models.FloatField()),
                ("health_center_accessibility", models.FloatField()),
                ("community_park_accessibility", models.FloatField()),
                ("fire_station_accessibility", models.FloatField()),
                ("population", models.FloatField()),
                ("theme_park_accessibility", models.FloatField()),
                ("parking_lot_accessibility", models.FloatField()),
                ("sports_facility_accessibility", models.FloatField()),
                ("elementary_school_accessibility", models.FloatField()),
                ("fast_charging", models.IntegerField()),
                ("agricultural_area", models.IntegerField()),
                ("average_altitude", models.IntegerField()),
                ("river", models.IntegerField()),
                ("center_coordinates", models.CharField(max_length=255)),
                ("coordinates", models.JSONField()),
            ],
        ),
    ]
