# Generated by Django 5.0.3 on 2024-03-28 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketTools", "0009_existinstalledgridgeo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecommandGSGEO",
        ),
    ]
