# Generated by Django 5.0.3 on 2024-03-28 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketTools", "0011_recommandgsgeo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="existInstalledGEO",
        ),
    ]
