# Generated by Django 5.0.3 on 2024-03-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketTools", "0012_delete_existinstalledgeo"),
    ]

    operations = [
        migrations.CreateModel(
            name="existInstalledGEO",
            fields=[
                ("unnamed_0", models.IntegerField(blank=True, null=True)),
                ("installation_year", models.IntegerField(verbose_name="설치년도")),
                ("address", models.CharField(max_length=255, verbose_name="주소")),
                (
                    "charging_station_name",
                    models.CharField(max_length=255, verbose_name="충전소명"),
                ),
                (
                    "facility_category_major",
                    models.CharField(max_length=255, verbose_name="시설구분(대)"),
                ),
                (
                    "facility_category_minor",
                    models.CharField(max_length=255, verbose_name="시설구분(소)"),
                ),
                (
                    "model_type_major",
                    models.CharField(max_length=255, verbose_name="기종(대)"),
                ),
                (
                    "model_type_minor",
                    models.CharField(max_length=255, verbose_name="기종(소)"),
                ),
                (
                    "operating_org_major",
                    models.CharField(max_length=255, verbose_name="운영기관(대)"),
                ),
                (
                    "operating_org_minor",
                    models.CharField(max_length=255, verbose_name="운영기관(소)"),
                ),
                (
                    "charger_type",
                    models.CharField(max_length=255, verbose_name="충전기타입"),
                ),
                (
                    "user_restriction",
                    models.CharField(max_length=255, verbose_name="이용자제한"),
                ),
                ("charger_id", models.IntegerField(verbose_name="충전기ID")),
                (
                    "charging_station_id",
                    models.CharField(max_length=255, verbose_name="충전소ID"),
                ),
                ("latitude", models.FloatField(verbose_name="위도")),
                ("longitude", models.FloatField(verbose_name="경도")),
                ("fid", models.IntegerField(blank=True, null=True)),
                (
                    "gid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("emd_cd", models.IntegerField(verbose_name="emd_cd")),
                ("emd_nm_k", models.CharField(max_length=255, verbose_name="emd_nm_k")),
                (
                    "charging_station_accessibility",
                    models.FloatField(verbose_name="충전소접근성"),
                ),
                ("gas_station_count", models.IntegerField(verbose_name="주유소_수")),
                ("charging_station_count", models.IntegerField(verbose_name="충전소_수")),
                (
                    "performance_facility_accessibility",
                    models.FloatField(verbose_name="공연시설접근성"),
                ),
                ("public_price", models.FloatField(verbose_name="공시지가")),
                ("library_accessibility", models.FloatField(verbose_name="도서관접근성")),
                ("hospital_accessibility", models.FloatField(verbose_name="병원접근성")),
                (
                    "health_center_accessibility",
                    models.FloatField(verbose_name="보건기관접근성"),
                ),
                (
                    "community_park_accessibility",
                    models.FloatField(verbose_name="생활권공원접근성"),
                ),
                (
                    "fire_station_accessibility",
                    models.FloatField(verbose_name="소방서접근성"),
                ),
                ("population", models.IntegerField(verbose_name="인구")),
                ("theme_park_accessibility", models.FloatField(verbose_name="주제공원접근성")),
                ("parking_lot_accessibility", models.FloatField(verbose_name="주차장접근성")),
                (
                    "sports_facility_accessibility",
                    models.FloatField(verbose_name="체육시설접근성"),
                ),
                (
                    "elementary_school_accessibility",
                    models.FloatField(verbose_name="초등학교접근성"),
                ),
                ("fast_charging", models.IntegerField(verbose_name="급/완속여부")),
                ("agricultural_area", models.IntegerField(verbose_name="농림지역")),
                ("altitude", models.IntegerField(verbose_name="고도")),
                ("river", models.IntegerField(verbose_name="하천")),
                (
                    "center_coordinates",
                    models.CharField(max_length=255, verbose_name="중심좌표"),
                ),
                ("y_pred_rf", models.IntegerField(blank=True, null=True)),
                ("y_pred_lgb", models.IntegerField(blank=True, null=True)),
                ("y_pred_xgb", models.IntegerField(blank=True, null=True)),
                ("y_pred_voting", models.IntegerField(blank=True, null=True)),
                ("cluster_id", models.IntegerField(blank=True, null=True)),
                ("cluster_size", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
