# Generated by Django 5.0.3 on 2024-03-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationInfo', '0002_alter_charging_station_info_charger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charging_station_info',
            name='Station_ID',
            field=models.TextField(default=''),
        ),
    ]
